[Icon Theme]
Name=Lucide KDE
Comment=Selected Lucide icons for KDE Plasma
Inherits=breeze
FollowsColorScheme=true
Directories=scalable/actions,scalable/applets,scalable/apps,scalable/devices,scalable/places,scalable/status

[scalable/actions]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Actions

[scalable/applets]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Applications

[scalable/apps]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Applications

[scalable/devices]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Devices

[scalable/places]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Places

[scalable/status]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Status

