[Icon Theme]
Name=Lucide KDE
Comment=Selected Lucide icons for KDE Plasma
Inherits=breeze
FollowsColorScheme=true
Directories=scalable/actions,scalable/applets,scalable/apps,scalable/categories,scalable/devices,scalable/emblems,scalable/emotes,scalable/mimetypes,scalable/places,scalable/preferences,scalable/status

[scalable/actions]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Actions

[scalable/applets]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Applications

[scalable/apps]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Applications

[scalable/categories]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Categories

[scalable/devices]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Devices

[scalable/emblems]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Emblems

[scalable/emotes]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Emotes

[scalable/mimetypes]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=MimeTypes

[scalable/places]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Places

[scalable/preferences]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Applications

[scalable/status]
Size=22
Type=Scalable
MinSize=16
MaxSize=64
Context=Status

